# Generated by Django 2.2.28 on 2025-12-22 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='제목')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='슬러그')),
                ('content', models.TextField(verbose_name='내용')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_published', models.BooleanField(default=False, verbose_name='발행됨')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '블로그 포스트',
                'verbose_name_plural': '블로그 포스트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='댓글 작성자')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_approved', models.BooleanField(default=True, verbose_name='승인됨')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post', verbose_name='포스트')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='blog_post_created_45f0c6_idx'),
        ),
    ]
